---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: nop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nop-pod
      labels:
        app: nop
    spec:
      containers:
        - name: spc
          image: yaswithaa/nop:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - name: webport
      port: 35001
      targetPort: 80
